# Generated by Django 5.1.6 on 2025-03-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrainte',
            fields=[
                ('idContrainte', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Couplage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('idCritere', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeElement', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('idObjectif', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRessource', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CouplageElementRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couplage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ij.couplage')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ij.element')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ij.ressource')),
            ],
        ),
        migrations.AddField(
            model_name='couplage',
            name='element',
            field=models.ManyToManyField(related_name='couplages', through='ij.CouplageElementRessource', to='ij.element'),
        ),
        migrations.AddField(
            model_name='couplage',
            name='ressource',
            field=models.ManyToManyField(related_name='couplages', through='ij.CouplageElementRessource', to='ij.ressource'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('idSolution', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.TextField()),
                ('couplages', models.ManyToManyField(related_name='solutions', to='ij.couplage')),
                ('solution', models.ManyToManyField(related_name='solutions', to='ij.objectif')),
            ],
        ),
    ]
