# Generated by Django 5.1.6 on 2025-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0002_alter_couplage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critere',
            name='description',
        ),
        migrations.AddField(
            model_name='critere',
            name='expression',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='critere',
            name='poids',
            field=models.FloatField(default=1.0),
        ),
    ]
