# Generated by Django 5.1.6 on 2025-03-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0003_remove_critere_description_critere_expression_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critere',
            name='poids',
        ),
        migrations.AddField(
            model_name='contrainte',
            name='idCriterefk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ij.critere'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='critere',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='critere',
            name='expression',
            field=models.TextField(),
        ),
    ]
