# Generated by Django 5.1.6 on 2025-03-18 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0004_remove_critere_poids_contrainte_idcriterefk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectif',
            name='type',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CouplageCritere',
            fields=[
                ('idValeur', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.FloatField()),
                ('couplage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ij.couplage')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ij.critere')),
            ],
        ),
        migrations.AddField(
            model_name='objectif',
            name='idCouplageCritere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ij.couplagecritere'),
            preserve_default=False,
        ),
    ]
