# Generated by Django 5.1.6 on 2025-03-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0005_objectif_type_couplagecritere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couplagecritere',
            name='critere',
        ),
        migrations.RemoveField(
            model_name='objectif',
            name='idCouplageCritere',
        ),
        migrations.AddField(
            model_name='objectif',
            name='idCritere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ij.critere'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couplagecritere',
            name='valeur',
            field=models.JSONField(),
        ),
    ]
