# Generated by Django 5.1.6 on 2025-03-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0007_rename_nom_contrainte_critere_cible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrainte',
            name='estAppliqueSolution',
            field=models.BooleanField(default=False),
        ),
    ]
