# Generated by Django 5.1.6 on 2025-03-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0008_contrainte_estappliquesolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='couplages',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='expression',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
